apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m38skwklm-go 
  janus-idp.io/tekton: m38skwklm-go
  backstage.io/kubernetes-id: m38skwklm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m38skwklm-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml